POST https://localhost:5001/api/v1/token HTTP/1.1
Authorization: Basic gznsww25X0uVHUSRk5NqHQ:zGG6Gpk48Ue2SKPr5-aZ0A
Content-Type: application/json

{
    "refreshToken": "udvkZp_HOUScReUU4Yc7qg"
}

###

GET https://localhost:5001/api/v1/list HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImNqZkxzWV9fVkVlSHJyODk0RmtqX2ciLCJuYmYiOjE2MTAyOTY0NjgsImV4cCI6MTYxMDI5ODI2OCwiaWF0IjoxNjEwMjk2NDY4LCJpc3MiOiJodHRwczovL3NtYWxsbGlzdGVyLm5vc3VjaGJsb2dnZXIuY29tIiwiYXVkIjoiaHR0cHM6Ly9zbWFsbGxpc3Rlci5ub3N1Y2hibG9nZ2VyLmNvbSJ9.Il0DH8wRAj0C4c6cuNpQJD00fr4YxX77zlbXIN7hF-A

###

GET https://localhost:5001/api/v1/list/none HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkZXZVFSZVBUeFUtZElaYTIyZlFEemciLCJuYmYiOjE2MTAyNzYzMTIsImV4cCI6MTYxMDI3ODExMiwiaWF0IjoxNjEwMjc2MzEyLCJpc3MiOiJodHRwczovL3NtYWxsbGlzdGVyLm5vc3VjaGJsb2dnZXIuY29tIiwiYXVkIjoiaHR0cHM6Ly9zbWFsbGxpc3Rlci5ub3N1Y2hibG9nZ2VyLmNvbSJ9.r2SelU6r9dSWhfr_HqyJ635P4IUAqyzNMswbJFH8GpE

###

GET https://localhost:5001/api/v1/list/3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IlRkcERoakoybWtPN0JDdldOTzZmREEiLCJuYmYiOjE2MTAzNTUwODIsImV4cCI6MTYxMDM1Njg4MiwiaWF0IjoxNjEwMzU1MDgyLCJpc3MiOiJodHRwczovL3NtYWxsbGlzdGVyLm5vc3VjaGJsb2dnZXIuY29tIiwiYXVkIjoiaHR0cHM6Ly9zbWFsbGxpc3Rlci5ub3N1Y2hibG9nZ2VyLmNvbSJ9.-IHw99jlajym-t1_47vlahU-816Weu9eIFH4YIfQYrM

###

POST https://localhost:5001/api/v1/item HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkZXZVFSZVBUeFUtZElaYTIyZlFEemciLCJuYmYiOjE2MTAyNzYzMTIsImV4cCI6MTYxMDI3ODExMiwiaWF0IjoxNjEwMjc2MzEyLCJpc3MiOiJodHRwczovL3NtYWxsbGlzdGVyLm5vc3VjaGJsb2dnZXIuY29tIiwiYXVkIjoiaHR0cHM6Ly9zbWFsbGxpc3Rlci5ub3N1Y2hibG9nZ2VyLmNvbSJ9.r2SelU6r9dSWhfr_HqyJ635P4IUAqyzNMswbJFH8GpE
Content-Type: application/json

{
    "listId": "3",
    "description": "milk",
    "dueDate": "2021-01-10T00:00:00",
    "notes": null
}
###

GET https://localhost:5001/feed/EOoWExcFO0mQBvWUmmGgtQ HTTP/1.1

###

